export type ModelModality = "text" | "image" | "audio" | "video" | "pdf" | "file";

export interface ModelCapability {
  modalities: ModelModality[];
  reasoning: boolean;
  thinkingEffort: string[] | null;
  context: number;
}

/**
 * Comprehensive model capabilities dictionary.
 * Keyed by normalized model name (same name = same model regardless of URL/provider).
 */
export const MODEL_CAPABILITIES: Record<string, ModelCapability> = {
  "aion-2.0": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "aion-3.0": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "aion-3.0-mini": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "aion-rp-llama-3.1-8b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 32768 },
  "auto": { modalities: ["text", "image", "audio", "file", "video"], reasoning: false, thinkingEffort: null, context: 2000000 },
  "auto-beta": { modalities: ["text", "image", "audio", "file", "video"], reasoning: false, thinkingEffort: null, context: 2000000 },
  "bodybuilder": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "claude-3-haiku": { modalities: ["text", "image", "pdf"], reasoning: false, thinkingEffort: null, context: 200000 },
  "claude-3-opus": { modalities: ["text", "image", "pdf"], reasoning: false, thinkingEffort: null, context: 200000 },
  "claude-3.5-haiku": { modalities: ["text", "image", "pdf"], reasoning: false, thinkingEffort: null, context: 200000 },
  "claude-3.5-sonnet": { modalities: ["text", "image", "pdf"], reasoning: false, thinkingEffort: null, context: 200000 },
  "claude-3.7-sonnet": { modalities: ["text", "image", "pdf"], reasoning: true, thinkingEffort: null, context: 200000 },
  "claude-fable-5": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high","xhigh","max"], context: 1000000 },
  "claude-fable-latest": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "claude-haiku-4-5": { modalities: ["text", "image", "pdf"], reasoning: true, thinkingEffort: null, context: 200000 },
  "claude-haiku-4.5": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: null, context: 200000 },
  "claude-haiku-latest": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 200000 },
  "claude-opus-4": { modalities: ["image", "text", "file", "pdf"], reasoning: true, thinkingEffort: null, context: 200000 },
  "claude-opus-4-5": { modalities: ["text", "image", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 200000 },
  "claude-opus-4.1": { modalities: ["image", "text", "file", "pdf"], reasoning: true, thinkingEffort: null, context: 200000 },
  "claude-opus-4.5": { modalities: ["file", "image", "text", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 200000 },
  "claude-opus-4.6": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high","max"], context: 1000000 },
  "claude-opus-4.7": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high","xhigh","max"], context: 1000000 },
  "claude-opus-4.7-fast": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "claude-opus-4.8": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high","xhigh","max"], context: 1000000 },
  "claude-opus-4.8-fast": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "claude-opus-5": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high","xhigh","max"], context: 1000000 },
  "claude-opus-5-fast": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "claude-opus-latest": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "claude-sonnet-4": { modalities: ["image", "text", "file", "pdf"], reasoning: true, thinkingEffort: null, context: 1000000 },
  "claude-sonnet-4-5": { modalities: ["text", "image", "pdf"], reasoning: true, thinkingEffort: null, context: 1000000 },
  "claude-sonnet-4.5": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: null, context: 1000000 },
  "claude-sonnet-4.6": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high","max"], context: 1000000 },
  "claude-sonnet-5": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high","xhigh","max"], context: 1000000 },
  "claude-sonnet-latest": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "codestral": { modalities: ["text", "pdf"], reasoning: false, thinkingEffort: null, context: 256000 },
  "codestral-2508": { modalities: ["text", "file"], reasoning: false, thinkingEffort: null, context: 256000 },
  "cogito-v2.1-671b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "command-a": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 256000 },
  "command-r-08-2024": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "command-r-plus-08-2024": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "command-r7b-12-2024": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "cydonia-24b-v4.1": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "deepseek-chat": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 163840 },
  "deepseek-chat-v3-0324": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 163840 },
  "deepseek-chat-v3.1": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 163840 },
  "deepseek-r1": { modalities: ["text"], reasoning: true, thinkingEffort: null, context: 163840 },
  "deepseek-r1-0528": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 163840 },
  "deepseek-r1-distill-llama-70b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 8192 },
  "deepseek-reasoner": { modalities: ["text"], reasoning: true, thinkingEffort: null, context: 163840 },
  "deepseek-v3": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 163840 },
  "deepseek-v3.1-terminus": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 163840 },
  "deepseek-v3.2": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 163840 },
  "deepseek-v3.2-exp": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 163840 },
  "deepseek-v4-flash": { modalities: ["text"], reasoning: true, thinkingEffort: ["high","xhigh"], context: 1048576 },
  "deepseek-v4-flash-0731": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "deepseek-v4-flash-latest": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "deepseek-v4-pro": { modalities: ["text"], reasoning: true, thinkingEffort: ["high","xhigh"], context: 1048576 },
  "dolphin-mistral-24b-venice-edition": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "doubao-seed-1.6": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "doubao-seed-2-1-pro": { modalities: ["text", "image", "video"], reasoning: true, thinkingEffort: null, context: 262144 },
  "doubao-seed-2.0-lite": { modalities: ["text", "image", "video"], reasoning: true, thinkingEffort: ["minimal","low","medium","high"], context: 262144 },
  "doubao-seed-2.0-mini": { modalities: ["text", "image", "video"], reasoning: true, thinkingEffort: ["minimal","low","medium","high"], context: 262144 },
  "ernie-4.5-vl-424b-a47b": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 123000 },
  "free": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 200000 },
  "fugu-ultra": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "fusion": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "gemini-1.5-flash": { modalities: ["text", "image", "audio", "video", "pdf"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "gemini-1.5-pro": { modalities: ["text", "image", "audio", "video", "pdf"], reasoning: false, thinkingEffort: null, context: 2000000 },
  "gemini-2.0-flash": { modalities: ["text", "image", "audio", "video", "pdf"], reasoning: true, thinkingEffort: null, context: 1048576 },
  "gemini-2.5-flash": { modalities: ["file", "image", "text", "audio", "video", "pdf"], reasoning: true, thinkingEffort: null, context: 1048576 },
  "gemini-2.5-flash-image": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 32768 },
  "gemini-2.5-flash-lite": { modalities: ["text", "image", "file", "audio", "video", "pdf"], reasoning: true, thinkingEffort: null, context: 1048576 },
  "gemini-2.5-pro": { modalities: ["text", "image", "file", "audio", "video", "pdf"], reasoning: true, thinkingEffort: null, context: 1048576 },
  "gemini-2.5-pro-preview": { modalities: ["file", "image", "text", "audio"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "gemini-2.5-pro-preview-05-06": { modalities: ["text", "image", "file", "audio", "video"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "gemini-3-flash-preview": { modalities: ["text", "image", "file", "audio", "video", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 1048576 },
  "gemini-3-pro-image": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "gemini-3-pro-image-preview": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 65536 },
  "gemini-3.1-flash-image": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "gemini-3.1-flash-image-preview": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 65536 },
  "gemini-3.1-flash-lite": { modalities: ["text", "image", "video", "file", "audio", "pdf"], reasoning: true, thinkingEffort: ["minimal","low","medium","high"], context: 1048576 },
  "gemini-3.1-flash-lite-image": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 65536 },
  "gemini-3.1-flash-lite-preview": { modalities: ["text", "image", "video", "file", "audio"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "gemini-3.1-pro-preview": { modalities: ["audio", "file", "image", "text", "video", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 1048576 },
  "gemini-3.1-pro-preview-customtools": { modalities: ["text", "audio", "image", "video", "file"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "gemini-3.5-flash": { modalities: ["text", "image", "video", "file", "audio", "pdf"], reasoning: true, thinkingEffort: ["minimal","low","medium","high"], context: 1048576 },
  "gemini-3.5-flash-lite": { modalities: ["text", "image", "video", "file", "audio", "pdf"], reasoning: true, thinkingEffort: ["minimal","low","medium","high"], context: 1048576 },
  "gemini-3.6-flash": { modalities: ["text", "image", "video", "file", "audio", "pdf"], reasoning: true, thinkingEffort: ["minimal","low","medium","high"], context: 1048576 },
  "gemini-3.6-pro": { modalities: ["text", "image", "audio", "video", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 1048576 },
  "gemini-flash-latest": { modalities: ["text", "image", "video", "file", "audio"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "gemini-pro-latest": { modalities: ["audio", "file", "image", "text", "video"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "gemma-2-27b-it": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 8192 },
  "gemma-3-12b-it": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 131072 },
  "gemma-3-27b-it": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 262144 },
  "gemma-3-4b-it": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 131072 },
  "gemma-3n-e4b-it": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 32768 },
  "gemma-4-26b-a4b-it": { modalities: ["image", "text", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "gemma-4-31b-it": { modalities: ["image", "text", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "glm-4.1v": { modalities: ["text", "image"], reasoning: true, thinkingEffort: null, context: 65536 },
  "glm-4.5": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "glm-4.5-air": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "glm-4.5v": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 65536 },
  "glm-4.6": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 204800 },
  "glm-4.6v": { modalities: ["image", "text", "video"], reasoning: false, thinkingEffort: null, context: 131072 },
  "glm-4.7": { modalities: ["text"], reasoning: true, thinkingEffort: null, context: 204800 },
  "glm-4.7-flash": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 202752 },
  "glm-4v": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 16384 },
  "glm-5": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 204800 },
  "glm-5-turbo": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 202752 },
  "glm-5.1": { modalities: ["text"], reasoning: true, thinkingEffort: null, context: 204800 },
  "glm-5.2": { modalities: ["text"], reasoning: true, thinkingEffort: ["high","xhigh"], context: 1048576 },
  "glm-5.2v": { modalities: ["text", "image", "video"], reasoning: true, thinkingEffort: null, context: 202752 },
  "glm-5v-turbo": { modalities: ["image", "text", "video"], reasoning: true, thinkingEffort: null, context: 202752 },
  "gpt-3.5-turbo": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 16385 },
  "gpt-3.5-turbo-0613": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 4095 },
  "gpt-3.5-turbo-16k": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 16385 },
  "gpt-3.5-turbo-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 4095 },
  "gpt-4": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 8191 },
  "gpt-4-turbo": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 128000 },
  "gpt-4-turbo-preview": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "gpt-4.1": { modalities: ["image", "text", "file"], reasoning: false, thinkingEffort: null, context: 1047576 },
  "gpt-4.1-mini": { modalities: ["image", "text", "file"], reasoning: false, thinkingEffort: null, context: 1047576 },
  "gpt-4.1-nano": { modalities: ["image", "text", "file"], reasoning: false, thinkingEffort: null, context: 1047576 },
  "gpt-4o": { modalities: ["text", "image", "file", "pdf"], reasoning: false, thinkingEffort: null, context: 128000 },
  "gpt-4o-2024-05-13": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 128000 },
  "gpt-4o-2024-08-06": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 128000 },
  "gpt-4o-2024-11-20": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 128000 },
  "gpt-4o-mini": { modalities: ["text", "image", "file", "pdf"], reasoning: false, thinkingEffort: null, context: 128000 },
  "gpt-4o-mini-2024-07-18": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 128000 },
  "gpt-5": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["minimal","low","medium","high"], context: 400000 },
  "gpt-5-2": { modalities: ["text", "image", "pdf"], reasoning: true, thinkingEffort: ["none","low","medium","high","xhigh"], context: 400000 },
  "gpt-5-2-codex": { modalities: ["text", "image"], reasoning: true, thinkingEffort: null, context: 400000 },
  "gpt-5-3-codex": { modalities: ["text", "image"], reasoning: true, thinkingEffort: null, context: 400000 },
  "gpt-5-6-luna": { modalities: ["text", "image", "pdf"], reasoning: true, thinkingEffort: ["none","low","medium","high","xhigh","max"], context: 1050000 },
  "gpt-5-6-sol": { modalities: ["text", "image", "pdf"], reasoning: true, thinkingEffort: ["none","low","medium","high","xhigh","max"], context: 1050000 },
  "gpt-5-6-terra": { modalities: ["text", "image", "pdf"], reasoning: true, thinkingEffort: ["none","low","medium","high","xhigh","max"], context: 1050000 },
  "gpt-5-codex": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-5-image": { modalities: ["image", "text", "file"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-5-image-mini": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-5-mini": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["minimal","low","medium","high"], context: 400000 },
  "gpt-5-nano": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["minimal","low","medium","high"], context: 400000 },
  "gpt-5-pro": { modalities: ["image", "text", "file"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-5.1": { modalities: ["image", "text", "file", "pdf"], reasoning: true, thinkingEffort: ["none","low","medium","high"], context: 400000 },
  "gpt-5.1-codex": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-5.1-codex-max": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-5.1-codex-mini": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-5.2": { modalities: ["file", "image", "text", "pdf"], reasoning: true, thinkingEffort: ["none","low","medium","high","xhigh"], context: 400000 },
  "gpt-5.2-chat": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "gpt-5.2-codex": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-5.2-pro": { modalities: ["image", "text", "file"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-5.3-chat": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 128000 },
  "gpt-5.3-codex": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-5.4": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["none","low","medium","high","xhigh"], context: 1050000 },
  "gpt-5.4-image-2": { modalities: ["image", "text", "file"], reasoning: false, thinkingEffort: null, context: 272000 },
  "gpt-5.4-mini": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-5.4-nano": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-5.4-pro": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 1050000 },
  "gpt-5.5": { modalities: ["file", "image", "text", "pdf"], reasoning: true, thinkingEffort: ["none","low","medium","high","xhigh"], context: 1050000 },
  "gpt-5.5-pro": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 1050000 },
  "gpt-5.6-luna": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 1050000 },
  "gpt-5.6-luna-pro": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 1050000 },
  "gpt-5.6-sol": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 1050000 },
  "gpt-5.6-sol-pro": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 1050000 },
  "gpt-5.6-terra": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 1050000 },
  "gpt-5.6-terra-pro": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 1050000 },
  "gpt-audio": { modalities: ["text", "audio"], reasoning: false, thinkingEffort: null, context: 128000 },
  "gpt-audio-mini": { modalities: ["text", "audio"], reasoning: false, thinkingEffort: null, context: 128000 },
  "gpt-chat-latest": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-latest": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 1050000 },
  "gpt-mini-latest": { modalities: ["file", "image", "text"], reasoning: false, thinkingEffort: null, context: 400000 },
  "gpt-oss-120b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "gpt-oss-20b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "gpt-oss-safeguard-20b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "granite-4.0-h-micro": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131000 },
  "granite-4.1-8b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "grok-3": { modalities: ["text", "image"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 131072 },
  "grok-3-mini": { modalities: ["text", "image"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 131072 },
  "grok-4": { modalities: ["text", "image", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 256000 },
  "grok-4.20": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 2000000 },
  "grok-4.20-multi-agent": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 2000000 },
  "grok-4.3": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "grok-4.5": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 500000 },
  "grok-build-0.1": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 256000 },
  "grok-latest": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 500000 },
  "hermes-3-llama-3.1-405b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "hermes-3-llama-3.1-70b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "hermes-4-405b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "hermes-4-70b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "hunyuan-a13b-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "hy3": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "hy3-preview": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "inkling": { modalities: ["text", "image", "audio"], reasoning: false, thinkingEffort: null, context: 524288 },
  "inkling-small": { modalities: ["text", "image", "audio"], reasoning: false, thinkingEffort: null, context: 524288 },
  "jamba-large-1.7": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 256000 },
  "kat-coder-air-v2.5": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 256000 },
  "kat-coder-pro-v2": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "kat-coder-pro-v2.5": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 256000 },
  "kimi-for-coding": { modalities: ["text"], reasoning: true, thinkingEffort: null, context: 262144 },
  "kimi-k2": { modalities: ["text"], reasoning: true, thinkingEffort: null, context: 131072 },
  "kimi-k2-0905": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "kimi-k2-thinking": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "kimi-k2.5": { modalities: ["text", "image"], reasoning: true, thinkingEffort: null, context: 262144 },
  "kimi-k2.6": { modalities: ["text", "image"], reasoning: true, thinkingEffort: null, context: 262144 },
  "kimi-k2.7-code": { modalities: ["text", "image"], reasoning: true, thinkingEffort: null, context: 262144 },
  "kimi-k3": { modalities: ["text", "image", "video", "pdf"], reasoning: true, thinkingEffort: ["low","high","max"], context: 1048576 },
  "kimi-latest": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "l3-lunaris-8b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 8192 },
  "l3.1-euryale-70b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "l3.3-euryale-70b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "laguna-s-2.1": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "laguna-xs-2.1": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "ling-2.6-1t": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "ling-2.6-flash": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "ling-3.0-flash": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "ling-3.0-tiny": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "llama-3.1-70b-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "llama-3.1-8b-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "llama-3.2-1b-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 60000 },
  "llama-3.2-3b-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "llama-3.3-70b-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "llama-4-maverick": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "llama-4-scout": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 1310720 },
  "llama-guard-4-12b": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "longcat-2.0": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1048756 },
  "lyria-3-clip-preview": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "lyria-3-pro-preview": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "magnum-v4-72b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 16384 },
  "mercury-2": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "mimo-v2.5": { modalities: ["text", "audio", "image", "video"], reasoning: false, thinkingEffort: null, context: 1050000 },
  "mimo-v2.5-pro": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1050000 },
  "minimax-01": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 1000192 },
  "minimax-m1": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "minimax-m2": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 204800 },
  "minimax-m2-her": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 65536 },
  "minimax-m2.1": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 204800 },
  "minimax-m2.5": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 204800 },
  "minimax-m2.7": { modalities: ["text"], reasoning: true, thinkingEffort: null, context: 204800 },
  "minimax-m2.7-highspeed": { modalities: ["text"], reasoning: true, thinkingEffort: null, context: 204800 },
  "minimax-m3": { modalities: ["text", "image", "video"], reasoning: true, thinkingEffort: null, context: 1048576 },
  "ministral": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 262144 },
  "ministral-14b-2512": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 262144 },
  "ministral-3b-2512": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 131072 },
  "ministral-8b-2512": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 262144 },
  "mistral-large": { modalities: ["text", "file", "image", "pdf"], reasoning: false, thinkingEffort: null, context: 262144 },
  "mistral-large-2407": { modalities: ["text", "file"], reasoning: false, thinkingEffort: null, context: 131072 },
  "mistral-large-2512": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 262144 },
  "mistral-medium-3": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 131072 },
  "mistral-medium-3-5": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 262144 },
  "mistral-medium-3.1": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 131072 },
  "mistral-nemo": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "mistral-saba": { modalities: ["text", "file"], reasoning: false, thinkingEffort: null, context: 32768 },
  "mistral-small": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 256000 },
  "mistral-small-24b-instruct-2501": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 32768 },
  "mistral-small-2603": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 262144 },
  "mistral-small-3.1-24b-instruct": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 128000 },
  "mistral-small-3.2-24b-instruct": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 256000 },
  "mixtral-8x22b-instruct": { modalities: ["text", "file"], reasoning: false, thinkingEffort: null, context: 65536 },
  "morph-v3-fast": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 81920 },
  "morph-v3-large": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "muse-spark-1.1": { modalities: ["text", "image", "video", "file", "audio"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "muse-spark-1.2": { modalities: ["text", "image", "video", "file", "audio"], reasoning: false, thinkingEffort: null, context: 1048576 },
  "mythomax-l2-13b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 8192 },
  "nemotron-3-nano-30b-a3b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 256000 },
  "nemotron-3-nano-omni-30b-a3b-reasoning": { modalities: ["text", "audio", "image", "video"], reasoning: false, thinkingEffort: null, context: 256000 },
  "nemotron-3-super-120b-a12b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "nemotron-3-ultra-550b-a55b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "nemotron-3.5-content-safety": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 128000 },
  "nemotron-nano-12b-v2-vl": { modalities: ["image", "text", "video"], reasoning: false, thinkingEffort: null, context: 128000 },
  "nemotron-nano-9b-v2": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "nex-n2-mini": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 262144 },
  "nex-n2-pro": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 262144 },
  "north-mini-code": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 256000 },
  "nova-2-lite-v1": { modalities: ["text", "image", "video", "file"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "nova-lite-v1": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 300000 },
  "nova-micro-v1": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "nova-premier-v1": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "nova-pro-v1": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 300000 },
  "o1": { modalities: ["text", "image", "file", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 200000 },
  "o1-mini": { modalities: ["text"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 128000 },
  "o1-pro": { modalities: ["text", "image", "file"], reasoning: false, thinkingEffort: null, context: 200000 },
  "o3": { modalities: ["image", "text", "file", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 200000 },
  "o3-mini": { modalities: ["text", "file", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 200000 },
  "o3-mini-high": { modalities: ["text", "file"], reasoning: false, thinkingEffort: null, context: 200000 },
  "o3-pro": { modalities: ["text", "file", "image", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 200000 },
  "o4-mini": { modalities: ["image", "text", "file", "pdf"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 200000 },
  "o4-mini-high": { modalities: ["image", "text", "file"], reasoning: false, thinkingEffort: null, context: 200000 },
  "olmo-3-32b-think": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 65536 },
  "palmyra-x5": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1040000 },
  "pareto-code": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 2000000 },
  "perceptron-mk1": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 32768 },
  "phi-4": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 16384 },
  "pixtral": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 128000 },
  "qwen-2.5-72b-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 32768 },
  "qwen-2.5-7b-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 32768 },
  "qwen-2.5-coder-32b-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 32768 },
  "qwen-plus": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen-plus-2025-07-28": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen2.5-omni": { modalities: ["text", "image", "audio", "video"], reasoning: false, thinkingEffort: null, context: 128000 },
  "qwen2.5-vl": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 128000 },
  "qwen2.5-vl-72b-instruct": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 128000 },
  "qwen3-14b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "qwen3-235b-a22b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "qwen3-235b-a22b-2507": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-235b-a22b-thinking-2507": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-30b-a3b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "qwen3-30b-a3b-instruct-2507": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-30b-a3b-thinking-2507": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 81920 },
  "qwen3-32b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "qwen3-8b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "qwen3-coder": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-coder-30b-a3b-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-coder-480b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-coder-480b-a35b-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-coder-flash": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen3-coder-next": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-coder-plus": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen3-max": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-max-thinking": { modalities: ["text"], reasoning: true, thinkingEffort: null, context: 262144 },
  "qwen3-next-80b-a3b-instruct": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-next-80b-a3b-thinking": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-vl": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-vl-235b-a22b-instruct": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-vl-235b-a22b-thinking": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 131072 },
  "qwen3-vl-30b-a3b-instruct": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-vl-30b-a3b-thinking": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-vl-32b-instruct": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 131072 },
  "qwen3-vl-8b-instruct": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3-vl-8b-thinking": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "qwen3.5-122b-a10b": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3.5-27b": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3.5-35b-a3b": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3.5-397b-a17b": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3.5-9b": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3.5-flash-02-23": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen3.5-plus": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen3.5-plus-02-15": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen3.5-plus-20": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen3.6-27b": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3.6-35b-a3b": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3.6-flash": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen3.6-max-preview": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "qwen3.6-plus": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen3.7-flash": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen3.7-max": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen3.7-plus": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "qwen3.8-max": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 1000000 },
  "reka-edge": { modalities: ["image", "text", "video"], reasoning: false, thinkingEffort: null, context: 16384 },
  "reka-flash-3": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 65536 },
  "relace-apply-3": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 256000 },
  "relace-search": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 256000 },
  "remm-slerp-l2-13b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 6144 },
  "ring-2.6-1t": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "rocinante-12b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 65536 },
  "seed-1.6": { modalities: ["image", "text", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "seed-1.6-flash": { modalities: ["image", "text", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "seed-2.0-lite": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "seed-2.0-mini": { modalities: ["text", "image", "video"], reasoning: false, thinkingEffort: null, context: 262144 },
  "skyfall-36b-v2": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 32768 },
  "solar-pro-3": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "sonar": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 127072 },
  "sonar-deep-research": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "sonar-pro": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 200000 },
  "sonar-pro-search": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 200000 },
  "sonar-reasoning-pro": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 128000 },
  "step-1o": { modalities: ["text"], reasoning: true, thinkingEffort: null, context: 32768 },
  "step-2.1-256k": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "step-2.5-vl": { modalities: ["text", "image"], reasoning: false, thinkingEffort: null, context: 32768 },
  "step-3-5-flash-2603": { modalities: ["text"], reasoning: true, thinkingEffort: null, context: 262144 },
  "step-3.5-flash": { modalities: ["text"], reasoning: true, thinkingEffort: null, context: 262144 },
  "step-3.7-flash": { modalities: ["text", "image", "video"], reasoning: true, thinkingEffort: ["low","medium","high"], context: 262144 },
  "trinity-large-thinking": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 262144 },
  "ui-tars-1.5-7b": { modalities: ["image", "text"], reasoning: false, thinkingEffort: null, context: 128000 },
  "unslopnemo-12b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 1024000 },
  "virtuoso-large": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 131072 },
  "voxtral-small-24b-2507": { modalities: ["text", "audio", "file"], reasoning: false, thinkingEffort: null, context: 32000 },
  "weaver": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 8000 },
  "wizardlm-2-8x22b": { modalities: ["text"], reasoning: false, thinkingEffort: null, context: 65535 },
};

/**
 * Normalize a model name for dictionary lookup.
 * Strips vendor prefix (openai/), :batch/:free suffix, date suffixes, case.
 */
export function normalizeModelName(name: string): string {
  return name
    .replace(/^.*\//, "")
    .replace(/:\w+$/, "")
    .replace(/[-_]?\d{6}$/, "")
    .toLowerCase()
    .replace(/\.(?!\d)/g, "-")
    .trim();
}

/** Look up capabilities by model name (normalized). Returns undefined if unknown. */
export function getModelCapability(modelName: string): ModelCapability | undefined {
  return MODEL_CAPABILITIES[normalizeModelName(modelName)];
}

/** Check whether a model supports the given modality. Unknown models fail open (assume supported). */
export function modelSupportsModality(modelName: string, modality: ModelModality): boolean {
  const cap = getModelCapability(modelName);
  if (!cap) return true;
  return cap.modalities.includes(modality);
}

/** Whether a model is multimodal (supports image/audio/video/pdf besides text). */
export function isModelMultimodal(modelName: string): boolean {
  const cap = getModelCapability(modelName);
  if (!cap) return false;
  return cap.modalities.some((m) => m !== "text");
}

/** Whether a model is a reasoning model. */
export function isReasoningModel(modelName: string): boolean {
  const cap = getModelCapability(modelName);
  if (!cap) return false;
  return cap.reasoning;
}

/** Supported thinking effort levels for a model. */
export function getThinkingEfforts(modelName: string): string[] | null {
  return getModelCapability(modelName)?.thinkingEffort ?? null;
}

/** Max context tokens for a model (0 = unknown). */
export function getModelContextLimit(modelName: string): number {
  return getModelCapability(modelName)?.context ?? 0;
}
